name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
        env:
          CI: true

      - name: Log PR Message
        run: |
          MESSAGE="We will add lint checks later"
          echo "::add-mask::$MESSAGE"
          echo "$MESSAGE"
